version: '3.9'

services:
# backend service definition
  backend:
    build: ./backend
    ports:
      - "8000:8000"

    environment:
      - DB_HOST=db
      - DB_NAME=appdb
      - DB_USER=postgres
      - DB_PASSWORD=password

    depends_on:
      - db


# Postgres database service definition
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql #this will run the init.sql script when the container starts

# Define a named volume for PostgreSQL data persistence
volumes:
  postgres_data: